title: "CAS Settings"
form_title: "CAS Configuration"
app_url_label: "Application URL"
app_url_placeholder: "Enter the application URL, e.g.: http://your-app-url.com"
base_path_label: "CAS Server Address"
base_path_placeholder: "Enter URL, e.g.: https://cas.example.com/cas"
login_uri_label: "Login URI"
login_uri_placeholder: "Enter login URI, e.g.: /login"
logout_uri_label: "Logout URI"
logout_uri_placeholder: "Enter logout URI, e.g.: /logout"
welcome_uri_label: "Welcome URI"
welcome_uri_placeholder: "Enter CAS homepage URI, e.g.: /index.html"
redirect_key_label: "Redirect URL Parameter Name"
redirect_key_placeholder: "Enter redirect URL parameter name, e.g.: service"
session_login_key_label: "Session Login Status Key"
session_login_key_placeholder: "Enter session login status key, e.g.: isSupwisdomCasLogin"
session_user_key_label: "Session User Info Key"
session_user_key_placeholder: "Enter session user info key, e.g.: supwisdomCasLoginUser"
email_suffix_label: "Email Suffix"
email_suffix_placeholder: "Enter email suffix, e.g.: @example.com"
info_message: "Please refresh the page to see changes after each modification"
