title: "CAS设置"
base_path_label: "CAS服务器地址"
base_path_placeholder: "请输入URL，例如：https://cas.example.com/cas"
login_uri_label: "登录URI"
login_uri_placeholder: "请输入登录URI，例如：/login"
logout_uri_label: "登出URI"
logout_uri_placeholder: "请输入登出URI，例如：/logout"
welcome_uri_label: "欢迎URI"
welcome_uri_placeholder: "请输入cas主页的URI，例如：/index.html"
redirect_key_label: "跳转URL的参数名"
redirect_key_placeholder: "请输入跳转URL的参数名，例如：service"
session_login_key_label: "Session中登录状态的Key"
session_login_key_placeholder: "请输入Session中登录状态的Key，例如：isSupwisdomCasLogin"
session_user_key_label: "Session中用户信息的Key"
session_user_key_placeholder: "请输入Session中用户信息的Key，例如：supwisdomCasLoginUser"
info_message: "CAS (Central Authentication Service) 是一种单点登录协议，允许用户使用同一组凭证登录多个应用。"